In [1]:
import cv2
import numpy as np

In [2]:
img=cv2.imread("C:\\Users\\srira\\OneDrive\\Desktop\\Pictures\\Screenshots\\Screenshot 2024-07-09 130944.png")

In [3]:
img

array([[[255, 254, 242],
        [255, 255, 240],
        [255, 255, 238],
        ...,
        [119,  98,   7],
        [119,  98,   7],
        [119,  98,   7]],

       [[255, 255, 243],
        [255, 255, 240],
        [255, 255, 239],
        ...,
        [119,  97,   8],
        [118,  96,   8],
        [118,  96,   8]],

       [[255, 255, 243],
        [255, 255, 240],
        [255, 255, 239],
        ...,
        [119,  97,   9],
        [119,  97,   9],
        [119,  97,   9]],

       ...,

       [[113, 107,  54],
        [110, 107,  52],
        [109, 105,  50],
        ...,
        [ 60,  60,  30],
        [ 60,  60,  30],
        [ 60,  60,  30]],

       [[112, 105,  52],
        [109, 104,  49],
        [107, 103,  48],
        ...,
        [ 59,  59,  29],
        [ 59,  59,  29],
        [ 60,  60,  30]],

       [[112, 103,  49],
        [109, 102,  46],
        [107, 100,  44],
        ...,
        [ 59,  59,  29],
        [ 59,  59,  29],
        [ 60,  60,  30]]

In [4]:
shp = img.shape

In [5]:
shp

(389, 594, 3)

In [6]:
size = img.size

In [7]:
size

693198

In [8]:
reshape_image = cv2.resize(img,(500,500))

In [9]:
reshape_image

array([[[255, 254, 242],
        [255, 255, 239],
        [255, 255, 237],
        ...,
        [119,  98,   7],
        [119,  98,   7],
        [119,  98,   7]],

       [[255, 255, 242],
        [255, 255, 239],
        [255, 255, 238],
        ...,
        [119,  97,   8],
        [118,  97,   8],
        [118,  97,   8]],

       [[255, 255, 242],
        [255, 255, 240],
        [255, 255, 239],
        ...,
        [119,  97,   9],
        [118,  96,   8],
        [118,  96,   8]],

       ...,

       [[112, 106,  52],
        [109, 105,  50],
        [107, 103,  48],
        ...,
        [ 59,  59,  29],
        [ 59,  59,  29],
        [ 60,  60,  30]],

       [[112, 104,  50],
        [108, 103,  47],
        [106, 101,  46],
        ...,
        [ 59,  59,  29],
        [ 59,  59,  29],
        [ 60,  60,  30]],

       [[112, 103,  49],
        [108, 101,  45],
        [106,  99,  43],
        ...,
        [ 59,  59,  29],
        [ 59,  59,  29],
        [ 60,  60,  30]]

In [10]:
cv2.imshow("image",img)
cv2.imshow("imgresize",reshape_image)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
px  =  img[200,201]

In [12]:
px

array([223, 208, 156], dtype=uint8)

In [13]:
img =cv2.imread("C:\\Users\\srira\\OneDrive\\Desktop\\Pictures\\Screenshots\\Screenshot 2024-05-23 222732.png")

In [14]:
r = cv2.selectROI("select the area",img)


cropped_image = img[int(r[1]):int(r[1]+r[3]),
                       int(r[0]):int(r[0]+r[2])]
cv2.imshow("Cropped Image",cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
cropped_image

array([[[201, 127,  19],
        [201, 127,  19],
        [202, 128,  20],
        ...,
        [221, 157,  77],
        [221, 161,  89],
        [218, 166, 100]],

       [[202, 129,  21],
        [202, 129,  21],
        [202, 129,  21],
        ...,
        [223, 162,  87],
        [223, 166,  99],
        [221, 172, 111]],

       [[203, 130,  22],
        [203, 130,  22],
        [203, 130,  22],
        ...,
        [223, 167,  99],
        [224, 172, 111],
        [222, 178, 122]],

       ...,

       [[ 40,  74,  29],
        [ 30,  65,  23],
        [ 42,  70,  25],
        ...,
        [ 71,  21,   1],
        [ 71,  21,   1],
        [ 71,  21,   1]],

       [[ 31,  71,  27],
        [ 24,  63,  21],
        [ 34,  64,  20],
        ...,
        [ 69,  22,   1],
        [ 69,  22,   1],
        [ 69,  22,   1]],

       [[ 22,  65,  23],
        [ 25,  66,  24],
        [ 32,  65,  20],
        ...,
        [ 67,  21,   1],
        [ 67,  21,   2],
        [ 67,  22,   2]]

In [17]:
cv2.imwrite("C:\\Users\\srira\\OneDrive\\Desktop\\Pictures\\Screenshots\\bird.png",cropped_image)

True

In [18]:
img =cv2.imread("C:\\Users\\srira\\OneDrive\\Desktop\\Pictures\\Screenshots\\Screenshot 2024-05-23 222732.png")

In [19]:
b,g,r = cv2.split(img)



cv2.imshow("image",img)
cv2.imshow("blue",b)
cv2.imshow("green",g)
cv2.imshow("red",r)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
cv2.imwrite("C:\\Users\\srira\\OneDrive\\Desktop\\Pictures\\Screenshots\\bird2.png",b)

True